# Generated by Django 5.2.17 on 2026-08-25 18:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('opening', 'Boshlang‘ich qoldiq'), ('in', 'Kirim'), ('out', 'Chiqim'), ('sale', 'Savdo'), ('adjustment', 'Qoldiqni to‘g‘rilash')], max_length=20, verbose_name='Harakat turi')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='O‘zgargan miqdor')),
                ('quantity_before', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Oldingi qoldiq')),
                ('quantity_after', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Keyingi qoldiq')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Bajargan foydalanuvchi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.product', verbose_name='Mahsulot')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='stores.store', verbose_name='Market')),
            ],
            options={
                'verbose_name': 'Ombor harakati',
                'verbose_name_plural': 'Ombor harakatlari',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['store', '-created_at'], name='inventory_store_created_idx'), models.Index(fields=['store', 'product', '-created_at'], name='inventory_product_date_idx'), models.Index(fields=['store', 'movement_type'], name='inventory_store_type_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_movement_quantity_positive'), models.CheckConstraint(condition=models.Q(('quantity_before__gte', 0)), name='inventory_movement_before_non_negative'), models.CheckConstraint(condition=models.Q(('quantity_after__gte', 0)), name='inventory_movement_after_non_negative'), models.UniqueConstraint(condition=models.Q(('movement_type', 'opening')), fields=('product',), name='inventory_one_opening_per_product')],
            },
        ),
    ]
