# Generated by Django 5.2.17 on 2026-09-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('opening', 'Boshlang‘ich qoldiq'), ('in', 'Kirim'), ('out', 'Chiqim'), ('sale', 'Savdo'), ('adjustment', 'Qoldiqni to‘g‘rilash'), ('sale_cancel', 'Savdo bekori')], max_length=20, verbose_name='Harakat turi'),
        ),
    ]
