# Generated by Django 5.2.17 on 2026-09-24 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0002_saleitem_cancellation_reason_saleitem_cancelled_at_and_more'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('cashier_created', 'Kassir yaratildi'), ('cashier_updated', 'Kassir ma’lumotlari yangilandi'), ('cashier_password_changed', 'Kassir paroli yangilandi'), ('cashier_activated', 'Kassir faollashtirildi'), ('cashier_blocked', 'Kassir bloklandi'), ('sale_cancelled', 'Savdo bekor qilindi'), ('stock_movement', 'Ombor harakati')], max_length=50, verbose_name='Harakat turi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Qo‘shimcha ma’lumot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Bajargan foydalanuvchi')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='sales.sale', verbose_name='Savdo')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='stores.store', verbose_name='Market')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Nishon foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Faoliyat yozuvi',
                'verbose_name_plural': 'Faoliyat tarixi',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['store', 'action'], name='audit_store_action_idx'), models.Index(fields=['store', '-created_at'], name='audit_store_created_idx')],
            },
        ),
    ]
