# Generated by Django 5.2.17 on 2026-08-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Market nomi')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Marketlar',
                'ordering': ['name'],
            },
        ),
    ]
