# Generated by Django 5.2.17 on 2026-08-26 04:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(max_length=32, unique=True, verbose_name='Savdo raqami')),
                ('status', models.CharField(choices=[('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='completed', max_length=20, verbose_name='Holati')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Karta')], max_length=20, verbose_name='To‘lov turi')),
                ('total', models.DecimalField(decimal_places=2, max_digits=28, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Jami summa')),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=28, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Mijoz bergan summa')),
                ('change_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=28, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Qaytim')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Savdo vaqti')),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Kassir')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='stores.store', verbose_name='Market')),
            ],
            options={
                'verbose_name': 'Savdo',
                'verbose_name_plural': 'Savdolar',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('barcode', models.CharField(blank=True, max_length=64, verbose_name='Barkod')),
                ('unit', models.CharField(choices=[('piece', 'Dona'), ('kg', 'Kilogramm')], max_length=10, verbose_name='O‘lchov birligi')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Miqdor')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Sotuv narxi')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Kelish narxi')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=28, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Qator summasi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='products.product', verbose_name='Mahsulot')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='sales.sale', verbose_name='Savdo')),
            ],
            options={
                'verbose_name': 'Sotilgan mahsulot',
                'verbose_name_plural': 'Sotilgan mahsulotlar',
                'ordering': ['pk'],
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['store', '-created_at'], name='sales_store_created_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['store', 'status'], name='sales_store_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('total__gt', 0)), name='sales_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('amount_received__gte', 0)), name='sales_received_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('change_amount__gte', 0)), name='sales_change_non_negative'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale', 'product'], name='sale_item_sale_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sale_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='sale_item_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__gte', 0)), name='sale_item_purchase_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='sale_item_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.UniqueConstraint(fields=('sale', 'product'), name='sales_unique_product_per_sale'),
        ),
    ]
