# Generated by Django 5.2.17 on 2026-09-24 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Bekor qilish sababi'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan vaqt'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_sales', to=settings.AUTH_USER_MODEL, verbose_name='Bekor qilgan foydalanuvchi'),
        ),
    ]
