# Generated by Django 5.2.17 on 2026-08-25 18:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, verbose_name='Barkod')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Kelish narxi')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Sotuv narxi')),
                ('stock_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Qoldiq')),
                ('unit', models.CharField(choices=[('piece', 'Dona'), ('kg', 'Kilogramm')], default='piece', max_length=10, verbose_name='O‘lchov birligi')),
                ('low_stock_threshold', models.DecimalField(decimal_places=3, default=Decimal('5'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Kam qoldiq chegarasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='stores.store', verbose_name='Market')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['store', 'name'], name='product_store_name_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('purchase_price__gte', 0)), name='product_purchase_price_non_negative'), models.CheckConstraint(condition=models.Q(('sale_price__gte', 0)), name='product_sale_price_non_negative'), models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='product_stock_quantity_non_negative'), models.CheckConstraint(condition=models.Q(('low_stock_threshold__gte', 0)), name='product_low_threshold_non_negative'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('barcode__isnull', False), models.Q(('barcode', ''), _negated=True)), fields=('store', 'barcode'), name='unique_active_barcode_per_store')],
            },
        ),
    ]
